# Generated by Django 5.2.13 on 2026-04-27 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('description_2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('weighted_distribution', models.IntegerField()),
                ('date', models.DateField()),
                ('period_weeks', models.IntegerField()),
                ('market', models.ForeignKey(db_column='market_fk', on_delete=django.db.models.deletion.CASCADE, to='market_data.market')),
                ('product', models.ForeignKey(db_column='product_fk', on_delete=django.db.models.deletion.CASCADE, to='market_data.product')),
            ],
            options={
                'db_table': 'sales_data',
            },
        ),
        migrations.CreateModel(
            name='SubBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(db_column='brand_fk', on_delete=django.db.models.deletion.CASCADE, to='market_data.brand')),
            ],
            options={
                'db_table': 'subbrand',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_brand',
            field=models.ForeignKey(db_column='sub_brand_fk', on_delete=django.db.models.deletion.CASCADE, to='market_data.subbrand'),
        ),
    ]
