# Generated by Django 5.2.13 on 2026-04-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
