# Generated by Django 5.2.13 on 2026-04-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_alter_data_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='weighted_distribution',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
