# Generated by Django 5.2.13 on 2026-04-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_alter_data_weighted_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='weighted_distribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
