# Generated by Django 5.2.13 on 2026-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_alter_data_weighted_distribution_nullable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('description',), name='uniq_brand_description'),
        ),
        migrations.AddConstraint(
            model_name='data',
            constraint=models.UniqueConstraint(fields=('market', 'product', 'date'), name='uniq_data_market_product_date'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.UniqueConstraint(fields=('description', 'description_2'), name='uniq_market_descriptions'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('description', 'sub_brand'), name='uniq_product_description_subbrand'),
        ),
        migrations.AddConstraint(
            model_name='subbrand',
            constraint=models.UniqueConstraint(fields=('description', 'brand'), name='uniq_subbrand_description_brand'),
        ),
    ]
