# Generated by Django 5.2.13 on 2026-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
